In [5]:
import numpy as np


In [6]:
a= np.array([1,2,3])

In [7]:
a.shape

(3,)

In [8]:
b= np.array([[1,2],[3,4]])

In [9]:
x = b.shape
print(b,x)

[[1 2]
 [3 4]] (2, 2)


In [10]:
b.itemsize

4

In [13]:
x= np.ones([5,5])

In [19]:
z= np.zeros([3,3])
print(x)
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [23]:
x[1:4,1:4]= z
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
y = np.full_like(x,4)
print(y)

[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]


In [31]:
u = np.full_like(z,2)
y[1:4,1:4] = u
y[2,2] = 0
print(y)

[[4. 4. 4. 4. 4.]
 [4. 2. 2. 2. 4.]
 [4. 2. 0. 2. 4.]
 [4. 2. 2. 2. 4.]
 [4. 4. 4. 4. 4.]]


In [32]:
print(u)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [35]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [49]:
#Repeat an array
arr = np.array([1,2,3])
np.repeat(arr, 3, axis = 0 ) # some error

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [50]:
print(r1)

[1 1 1 2 2 2 3 3 3]


#### Be careful while copying arrays

In [54]:
a = np.array([1,2,3])

In [55]:
b = a

In [56]:
print(b)

[1 2 3]


In [57]:
b[0] = 100

In [58]:
print(b)

[100   2   3]


In [59]:
print(a) 

[100   2   3]


array a also changes while changing element on b. This is coz Python sees both b and a as pointing to the same element

---

#### How to copy?

In [61]:
a= np.array([1,2,3])
b = a.copy()  # Use copy function

In [63]:
b

array([1, 2, 3])

In [64]:
b[0] = 100
print(b)

[100   2   3]


In [65]:
print(a)

[1 2 3]


----

### Mathematics

In [66]:
n1 = np.array([1,2,3,4])
print(n1)
print(n1+2)

[1 2 3 4]
[3 4 5 6]


In [71]:
print(n1-2)
print(n1*2)

[-1  0  1  2]
[2 4 6 8]


In [72]:
n1**2

array([ 1,  4,  9, 16], dtype=int32)

In [73]:
#Take sine of all values
np.sin(n1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [75]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

---

#### Linear Algebra

In [76]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)  # This is a matrix multiply function

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [78]:
q1 = np.array([[1,2,3],[4,5,6]])
print(q1)

[[1 2 3]
 [4 5 6]]


In [79]:
q2 = np.array([[1,2],[3,4],[5,6]])
print(q2)

[[1 2]
 [3 4]
 [5 6]]


In [80]:
x = np.matmul(q1,q2)
print(x)

[[22 28]
 [49 64]]


In [82]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c) # This is linear algebra. determinant fn

1.0

In [83]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

---

#### Statistics

In [85]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.min(stats)

1

In [87]:
np.max(stats, axis=1)

array([3, 6])

In [88]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [89]:
np.sum(stats, axis=1)

array([ 6, 15])

---

#### Reorganizing Arrays

In [94]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)
after1 = before.reshape((2,2,2))
print(after1)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [95]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [100]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### Boolean Masking and Advanced Indexing

In [101]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [128]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [116]:
## You can index with a list in NumPy
a = np.array(([1,2,3,4,5,6,7,8,9]))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
a[[1,2,3]]

array([2, 3, 4])

In [119]:
np.any(filedata>50, axis = 0) ## Specifying axis = 0 it looks down vertically 

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [121]:
np.any(filedata>50, axis = 1) # looking horizontally

array([ True,  True,  True])

In [123]:
np.all(filedata>50, axis = 0)  # apply logic and figure it out

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [125]:
(((filedata > 50) & (filedata < 100)))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [126]:
(~((filedata > 50) & (filedata < 100))) ## ~ means not

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])